### ISSUE TITLE
ubuntu1604_libcxx_release should use standard libcxx library

### ISSUE THREAD

**Issue by danblick** [GoogleCloudPlatform/layer-definitions#107]
Hi,

Currently, one of the dependencies used in the "clang" layer is "ubuntu1604_libcxx_release".  In deps.bzl, the "libcxx-msan_" version of this library is specified.

https://github.com/GoogleCloudPlatform/layer-definitions/blob/947df3b0c68e34177d764eb2c77b58307389665e/layers/ubuntu1604/clang/deps.bzl#L42

When the "libcxx-msan_" library is used, the libraries included in the image will contain some undefined references to "msan"-related symbols.

This causes problems when trying to create statically linked binaries in the container (which I'm trying to do so that I can compile code using C++17 and libc++).

To reproduce the problem, create a simple cc_binary target with `features = ["fully_static_link"]`:

BUILD:
```
cc_binary(
    name = "helloworld",
    srcs = ["helloworld.cc"],
    features = ["fully_static_link"],
)
```

helloworld.cc:
```
#include <iostream>

int main(int argc, char** argv) {
  std::cout << "Hello world!" << std::endl;
  return 0;
}
```

Then compile the code using libc++.  Here i'm using the docker container from the cloud marketplace:

```
docker run \
  --mount type=bind,source=/src/workspace,destination=/src/workspace,readonly \
  --mount type=bind,source=/tmp/build_output,destination=/tmp/build_output \
  --workdir=/src/workspace \
  gcr.io/cloud-marketplace-containers/google/bazel@sha256:ecc5b033f2f0a880949838a8818c660f136383c5c24d142bde5e6933d0e28fc7 \
  --output_base=/tmp/build_output/output_base \
  --output_user_root=/tmp/build_output/output_user_root \
  build \
  --symlink_prefix=/ \
  --cxxopt=-std=c++17 \
  --cxxopt=-nostdinc++ \
  --cxxopt=-I/usr/local/include/c++/v1 \
  --linkopt=-stdlib=libc++ \
  --linkopt=-L/usr/local/lib \
  --linkopt=-Wl,-rpath,/usr/local/lib \
  --linkopt=-lc++ \
  --linkopt=-lc++abi \
  --linkopt=-pthread \
  //:helloworld
```

You'll get an error like:
```
(13:25:54) ERROR: /src/workspace/helloworld/BUILD:1:1: Linking of rule '//:helloworld' failed (Exit 1) clang failed: error executing command /usr/local/bin/clang -o bazel-out/k8-fastbuild/bin/helloworld '-stdlib=libc++' -L/usr/local/lib -Wl,-rpath,/usr/local/lib -pthread -Wl,-S '-fuse-ld=gold' -Wl,-no-as-needed ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/tmp/clang-build/src/libcxx/include/string:608: error: undefined reference to '__msan_param_tls'
/tmp/clang-build/src/libcxx/include/stdexcept:249: error: undefined reference to '__msan_param_tls'
/tmp/clang-build/src/libcxx/include/stdexcept:329: error: undefined reference to '__msan_retval_tls'
/tmp/clang-build/src/libcxx/include/string:615: error: undefined reference to '__msan_param_tls'
/tmp/clang-build/src/libcxx/include/stdexcept:260: error: undefined reference to '__msan_param_tls'
/tmp/clang-build/src/libcxx/include/stdexcept:340: error: undefined reference to '__msan_retval_tls'

```

The fix is to point to the regular non-msan version of the libcxx libraries, which you can also do by adding an entry to WORKSPACE to override the `ubuntu1604_libcxx_release` dependency:

```
http_file(
    name = "ubuntu1604_libcxx_release",
    downloaded_file_path = "clang-ubuntu16_04/libcxx_r352865.tar.gz",
    sha256 = "31736d14525263bf1bf4daa7ae937eebaf7a9d5433734307962d3f544cfd6260",
    urls = ["https://storage.googleapis.com/clang-builds-stable/clang-ubuntu16_04/libcxx_r352865.tar.gz"],
)

```

To verify that changing this to the standard version of "libcxx" solves the problem, rebuild the container and retry the build using the generated image:

```
load(
    "@bazel_toolchains//rules/container:docker_toolchains.bzl",
    "toolchain_container",
)

toolchain_container(
    name = "build",
    base = "@ubuntu1604//image",
    # Remove non-deterministic files.
    installation_cleanup_commands = "rm -f /etc/init.d/.depend.boot /etc/init.d/.depend.start /etc/init.d/.depend.stop",
    language_layers = [
        "@layer_definitions//layers/ubuntu1604/clang:clang-ltl",
        "@layer_definitions//layers/ubuntu1604/java:java-ltl",
        "@layer_definitions//layers/ubuntu1604/java:java11-ltl",
        "@layer_definitions//layers/ubuntu1604/python:python-ltl",
        "@layer_definitions//layers/ubuntu1604/bazel:bazel-ltl",
        "@layer_definitions//layers/ubuntu1604/docker:docker-ltl",
    ],
    tags = ["manual"],
)

load("@io_bazel_rules_docker//container:container.bzl", "container_push")

container_push(
    name = "push_build",
    format = "Docker",
    image = ":build",
    registry = "gcr.io",
    repository = "replaceme/build",
    tags = ["manual"],
)
```

**Comment by xingao267** [comment]
@ilya-biryukov could you help take a look at this? We've been using libcxx-msan_*.tar.gz since the beginning. If we switch to use libcxx_*.tar.gz, can we still properly do msan builds?

**Comment by nlopezgi** [comment]
Hi @danblick we use the "libcxx-msan_" version of the library in order to enable msan builds out of the box with this container. This is an important use case for our container and one we cannot stop supporting. Can you tell us a bit more about your use case, why you are using the Bazel container and how the current issues impact you? Its very possible we cannot support both the msan use case and your use case at the same time with one single container, if so, you might need to create a custom container with the right library yourself (we could consider hosting an alternate version of the clang layer in bazel-toolchains repo).

**Comment by danblick** [comment]
Hi @nlopezgi , my goal was just to build C++17 binaries in the container and run them in an environment without clang's libc++ installed.  I'm alreadly doing this with a custom container including the non-msan version of libc++ and then creating statically-linked binaries. I reported this as a bug since it seems like a bug that the Bazel build container can't create statically linked binaries (maybe it just needs other msan libraries installed too)?  It would be great if there were a version of the container available that could work for this use case.  (Actually since my goal is just compiling code with C++17 I'd be happy with any supported workflow that let me do that.)

**Comment by nlopezgi** [comment]
hi @danblick 
thanks for the additional clarifications, we will see if its possible to support your use case w/o breaking support for msan and get back as soon as we have more info.

**Comment by ilya-biryukov** [comment]
Does that mean we are shipping and using libcxx_msan for all **non-msan** builds?

These errors suggest that we end up using the sanitized builds of libc++ in normal (no sanitizers) mode.
Adding `-fsanitize=memory` as a `--cxxopt ` and `--linkopt` would fix the linker errors, but we should not be using msan version of libc++ for non-sanitized builds.

**Comment by danblick** [comment]
Note that "bazel run" in the container doesn't work either for targets compiled using clang's libc++:

https://github.com/danblick/layer-definitions/blob/issue-107-repro/helloworld

Output:
```
$ sh run.sh 
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //:helloworld-cxx17 (1 packages loaded, 0 targets configured)
INFO: Analysed target //:helloworld-cxx17 (9 packages loaded, 65 targets configured).
INFO: Found 1 target...
[2 / 6] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //:helloworld-cxx17 up-to-date:
  /tmp/helloworld_build/output_base/execroot/__main__/bazel-out/k8-fastbuild/bin/helloworld-cxx17
INFO: Elapsed time: 2.018s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /tmp/helloworld_build/output_base/execroot/__main__/bazel-out/k8-fastbuild/bin/helloworld-cxx17
INFO: Build completed successfully, 1 total action
/tmp/helloworld_build/output_base/execroot/__main__/bazel-out/k8-fastbuild/bin/helloworld-cxx17: symbol lookup error: /usr/local/lib/libc++abi.so.1: undefined symbol: __msan_va_arg_overflow_size_tls

```

**Comment by ilya-biryukov** [comment]
That confirms that the msan version of libcxx is used for **all** builds.
@xingao267, @nlopezgi, we should be shipping and using the non-msan build of `libcxx` by default.

Do we ship separate containers for sanitized builds or should all builds be possible inside a single all-batteries-included container? (My guess is the latter, but I don't have the full context there).
If we have separate containers, the fix is obvious - we could just ship different versions of libcxx in msan vs non-msan container.
If we need to ship in a single container I suggest shipping multiple builds of libcxx in separate folders, e.g.:
- `/usr/local/libcxx-release/` for release builds
- `/usr/local/libcxx-msan/` for msan builds
- `/usr/local/libcxx-tsan/` for tsan builds

Depending on the configuration, we need proper flags in the crosstool to point to the right version of the library.

**Comment by nlopezgi** [comment]
thanks for looking into this @ilya-biryukov and @danblick ,
I will be running some tests this week to try to package both versions of libcxx and use bazel configuration to select the right one. I'll ping back this thread once I have results. If this does not work, we'll probably need to produce a separate container for msan.

**Comment by nlopezgi** [comment]
Hi @danblick ,
I looked in detail at the issue today. Here's what I found:

- Builds on Bazel use by default libstdc++ for their builds. We ship in our container a vanilla version of libstdc++-4.9-dev which is used by most Bazel builds.
- We ship a version of libc++ with our Bazel and RBE containers _specifically_ to support the msan use case (i.e., msan cannot compile with libstdc++). Otherwise, we would likely not ship libc++ in our container as libstdc++ would be sufficient for most use cases.
- I installed in the bazel container the libc++ vanilla version https://storage.googleapis.com/clang-builds-stable/clang-ubuntu16_04/libcxx_r356814.tar.gz. I installed in a different directory `/usr/local/libcxx-vanilla/`. I ran a Bazel build successfully by passing some additional flags:
```
export CPLUS_INCLUDE_PATH=/usr/local/libcxx-vanilla/ bazel build \
  --symlink_prefix=/ \
  --cxxopt=-std=c++17 \
  --cxxopt=-nostdinc++ \
  --cxxopt=-I/usr/local/libcxx-vanilla/include/c++/v1 \
  --linkopt=-stdlib=libc++ \
  --linkopt=-L/usr/local/libcxx-vanilla/lib \
  --linkopt=-Wl,-rpath,/usr/local/libcxx-vanilla/lib \
  --linkopt=-lc++ \
  --linkopt=-lc++abi \
  --linkopt=-pthread \
  //:helloworld
``` 

-  My overall conclusion is that it is indeed the case that our container does not support building with clang's libc++ unless its for msan compilation, and that this is working as intended.
- We will not be bundling a vanilla version of libc++ in our container as this will cause bloat and its not a use case we are currently interested in supporting.
- For your specific use case you should be able to extend from our container to install the libc++ version that you need for your builds.
- We might reconsider this decision if we see a large number of users also request this use case or if Bazel decides to support libc++ as a default.
